umrr_can_publisher_RL:
  frame_id: "radar_RL"
  can_socket: "can3"
  debug: 0
  # parameters to send to sensor
  antenna_mode: {section: 3016, parameter: 0, value: 1}
  # center_frequency: {section: 3016, parameter: 5, value: 2}
